apiVersion: v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      app: my-daemonset
  template:
    metadata:
      app: my-daemonset
  spec:
    containers:
    - name: nginx
      image: nginx:1.19.1